// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "myproject.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic myproject::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic myproject::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> myproject::ap_ST_fsm_pp0_stage0 = "1";
const bool myproject::ap_const_boolean_1 = true;
const sc_lv<32> myproject::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool myproject::ap_const_boolean_0 = false;

myproject::myproject(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30 = new dense_latency_0_0_0_0_0_0_0_0_0_0_0_1("grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30");
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_clk(ap_clk);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_rst(ap_rst);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->data_V_read(input1_V);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_0(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_0);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_1(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_1);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_2(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_2);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_3(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_3);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_4(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_4);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_5(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_5);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_6(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_6);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_7(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_7);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_8(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_8);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_return_9(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_9);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30->ap_ce(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36 = new dense_latency_0_0_0_0_0_0_0_0_0_0_0("grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36");
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_clk(ap_clk);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_rst(ap_rst);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_0_V_read(layer3_out_0_V_reg_199);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_1_V_read(layer3_out_1_V_reg_204);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_2_V_read(layer3_out_2_V_reg_209);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_3_V_read(layer3_out_3_V_reg_214);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_4_V_read(layer3_out_4_V_reg_219);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_5_V_read(layer3_out_5_V_reg_224);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_6_V_read(layer3_out_6_V_reg_229);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_7_V_read(layer3_out_7_V_reg_234);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_8_V_read(layer3_out_8_V_reg_239);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->data_9_V_read(layer3_out_9_V_reg_244);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_0(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_0);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_1(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_1);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_2(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_2);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_3(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_3);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_4(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_4);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_5(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_5);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_6(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_6);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_7(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_7);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_8(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_8);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_return_9(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_9);
    grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36->ap_ce(grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50 = new relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s("call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50");
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_ready(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_ready);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_0_V_read(layer2_out_0_V_reg_149);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_1_V_read(layer2_out_1_V_reg_154);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_2_V_read(layer2_out_2_V_reg_159);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_3_V_read(layer2_out_3_V_reg_164);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_4_V_read(layer2_out_4_V_reg_169);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_5_V_read(layer2_out_5_V_reg_174);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_6_V_read(layer2_out_6_V_reg_179);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_7_V_read(layer2_out_7_V_reg_184);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_8_V_read(layer2_out_8_V_reg_189);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->data_9_V_read(layer2_out_9_V_reg_194);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_0(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_0);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_1(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_1);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_2(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_2);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_3(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_3);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_4(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_4);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_5(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_5);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_6(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_6);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_7(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_7);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_8(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_8);
    call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50->ap_return_9(call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_9);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_start );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp19);
    sensitive << ( ap_start );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp50);
    sensitive << ( ap_start );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_start );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9_ignore_call26);

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter9_ignore_call4);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10_ignore_call26);

    SC_METHOD(thread_ap_block_state11_pp0_stage0_iter10_ignore_call4);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter11);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter11_ignore_call26);

    SC_METHOD(thread_ap_block_state12_pp0_stage0_iter11_ignore_call4);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter12);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter12_ignore_call26);

    SC_METHOD(thread_ap_block_state13_pp0_stage0_iter12_ignore_call4);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter13);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter13_ignore_call26);

    SC_METHOD(thread_ap_block_state14_pp0_stage0_iter13_ignore_call4);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter14);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter14_ignore_call26);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter14_ignore_call4);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter15);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter15_ignore_call26);

    SC_METHOD(thread_ap_block_state16_pp0_stage0_iter15_ignore_call4);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter16);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter16_ignore_call26);

    SC_METHOD(thread_ap_block_state17_pp0_stage0_iter16_ignore_call4);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);
    sensitive << ( ap_start );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call26);
    sensitive << ( ap_start );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call4);
    sensitive << ( ap_start );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call26);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call4);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call26);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter2_ignore_call4);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call26);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter3_ignore_call4);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4_ignore_call26);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter4_ignore_call4);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5_ignore_call26);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter5_ignore_call4);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6_ignore_call26);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter6_ignore_call4);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7_ignore_call26);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter7_ignore_call4);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8_ignore_call26);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter8_ignore_call4);

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );

    SC_METHOD(thread_ap_idle_pp0_0to15);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to15 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_0 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_2 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_3 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_4 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_5 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_6 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_7 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_8 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_9 );

    SC_METHOD(thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp19 );

    SC_METHOD(thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp50 );

    SC_METHOD(thread_input1_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( input1_V_ap_vld );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter15 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter16 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "myproject_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input1_V_ap_vld, "(port)input1_V_ap_vld");
    sc_trace(mVcdFile, input1_V, "(port)input1_V");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
    sc_trace(mVcdFile, input1_V_blk_n, "(port)input1_V_blk_n");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter15, "ap_enable_reg_pp0_iter15");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter16, "ap_enable_reg_pp0_iter16");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2, "ap_block_state3_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3, "ap_block_state4_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4, "ap_block_state5_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5, "ap_block_state6_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6, "ap_block_state7_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7, "ap_block_state8_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8, "ap_block_state9_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9, "ap_block_state10_pp0_stage0_iter9");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10, "ap_block_state11_pp0_stage0_iter10");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter11, "ap_block_state12_pp0_stage0_iter11");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter12, "ap_block_state13_pp0_stage0_iter12");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter13, "ap_block_state14_pp0_stage0_iter13");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter14, "ap_block_state15_pp0_stage0_iter14");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter15, "ap_block_state16_pp0_stage0_iter15");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter16, "ap_block_state17_pp0_stage0_iter16");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, layer2_out_0_V_reg_149, "layer2_out_0_V_reg_149");
    sc_trace(mVcdFile, layer2_out_1_V_reg_154, "layer2_out_1_V_reg_154");
    sc_trace(mVcdFile, layer2_out_2_V_reg_159, "layer2_out_2_V_reg_159");
    sc_trace(mVcdFile, layer2_out_3_V_reg_164, "layer2_out_3_V_reg_164");
    sc_trace(mVcdFile, layer2_out_4_V_reg_169, "layer2_out_4_V_reg_169");
    sc_trace(mVcdFile, layer2_out_5_V_reg_174, "layer2_out_5_V_reg_174");
    sc_trace(mVcdFile, layer2_out_6_V_reg_179, "layer2_out_6_V_reg_179");
    sc_trace(mVcdFile, layer2_out_7_V_reg_184, "layer2_out_7_V_reg_184");
    sc_trace(mVcdFile, layer2_out_8_V_reg_189, "layer2_out_8_V_reg_189");
    sc_trace(mVcdFile, layer2_out_9_V_reg_194, "layer2_out_9_V_reg_194");
    sc_trace(mVcdFile, layer3_out_0_V_reg_199, "layer3_out_0_V_reg_199");
    sc_trace(mVcdFile, layer3_out_1_V_reg_204, "layer3_out_1_V_reg_204");
    sc_trace(mVcdFile, layer3_out_2_V_reg_209, "layer3_out_2_V_reg_209");
    sc_trace(mVcdFile, layer3_out_3_V_reg_214, "layer3_out_3_V_reg_214");
    sc_trace(mVcdFile, layer3_out_4_V_reg_219, "layer3_out_4_V_reg_219");
    sc_trace(mVcdFile, layer3_out_5_V_reg_224, "layer3_out_5_V_reg_224");
    sc_trace(mVcdFile, layer3_out_6_V_reg_229, "layer3_out_6_V_reg_229");
    sc_trace(mVcdFile, layer3_out_7_V_reg_234, "layer3_out_7_V_reg_234");
    sc_trace(mVcdFile, layer3_out_8_V_reg_239, "layer3_out_8_V_reg_239");
    sc_trace(mVcdFile, layer3_out_9_V_reg_244, "layer3_out_9_V_reg_244");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_0, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_0");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_1, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_1");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_2, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_2");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_3, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_3");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_4, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_4");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_5, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_5");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_6, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_6");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_7, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_7");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_8, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_8");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_9, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_9");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call4, "ap_block_state1_pp0_stage0_iter0_ignore_call4");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call4, "ap_block_state2_pp0_stage0_iter1_ignore_call4");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call4, "ap_block_state3_pp0_stage0_iter2_ignore_call4");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call4, "ap_block_state4_pp0_stage0_iter3_ignore_call4");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4_ignore_call4, "ap_block_state5_pp0_stage0_iter4_ignore_call4");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5_ignore_call4, "ap_block_state6_pp0_stage0_iter5_ignore_call4");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6_ignore_call4, "ap_block_state7_pp0_stage0_iter6_ignore_call4");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7_ignore_call4, "ap_block_state8_pp0_stage0_iter7_ignore_call4");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8_ignore_call4, "ap_block_state9_pp0_stage0_iter8_ignore_call4");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9_ignore_call4, "ap_block_state10_pp0_stage0_iter9_ignore_call4");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10_ignore_call4, "ap_block_state11_pp0_stage0_iter10_ignore_call4");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter11_ignore_call4, "ap_block_state12_pp0_stage0_iter11_ignore_call4");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter12_ignore_call4, "ap_block_state13_pp0_stage0_iter12_ignore_call4");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter13_ignore_call4, "ap_block_state14_pp0_stage0_iter13_ignore_call4");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter14_ignore_call4, "ap_block_state15_pp0_stage0_iter14_ignore_call4");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter15_ignore_call4, "ap_block_state16_pp0_stage0_iter15_ignore_call4");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter16_ignore_call4, "ap_block_state17_pp0_stage0_iter16_ignore_call4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp19, "ap_block_pp0_stage0_11001_ignoreCallOp19");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_0, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_0");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_1, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_1");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_2, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_2");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_3, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_3");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_4, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_4");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_5, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_5");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_6, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_6");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_7, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_7");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_8, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_8");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_9, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_9");
    sc_trace(mVcdFile, grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce, "grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call26, "ap_block_state1_pp0_stage0_iter0_ignore_call26");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call26, "ap_block_state2_pp0_stage0_iter1_ignore_call26");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter2_ignore_call26, "ap_block_state3_pp0_stage0_iter2_ignore_call26");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter3_ignore_call26, "ap_block_state4_pp0_stage0_iter3_ignore_call26");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter4_ignore_call26, "ap_block_state5_pp0_stage0_iter4_ignore_call26");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter5_ignore_call26, "ap_block_state6_pp0_stage0_iter5_ignore_call26");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter6_ignore_call26, "ap_block_state7_pp0_stage0_iter6_ignore_call26");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter7_ignore_call26, "ap_block_state8_pp0_stage0_iter7_ignore_call26");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter8_ignore_call26, "ap_block_state9_pp0_stage0_iter8_ignore_call26");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter9_ignore_call26, "ap_block_state10_pp0_stage0_iter9_ignore_call26");
    sc_trace(mVcdFile, ap_block_state11_pp0_stage0_iter10_ignore_call26, "ap_block_state11_pp0_stage0_iter10_ignore_call26");
    sc_trace(mVcdFile, ap_block_state12_pp0_stage0_iter11_ignore_call26, "ap_block_state12_pp0_stage0_iter11_ignore_call26");
    sc_trace(mVcdFile, ap_block_state13_pp0_stage0_iter12_ignore_call26, "ap_block_state13_pp0_stage0_iter12_ignore_call26");
    sc_trace(mVcdFile, ap_block_state14_pp0_stage0_iter13_ignore_call26, "ap_block_state14_pp0_stage0_iter13_ignore_call26");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter14_ignore_call26, "ap_block_state15_pp0_stage0_iter14_ignore_call26");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage0_iter15_ignore_call26, "ap_block_state16_pp0_stage0_iter15_ignore_call26");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage0_iter16_ignore_call26, "ap_block_state17_pp0_stage0_iter16_ignore_call26");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp50, "ap_block_pp0_stage0_11001_ignoreCallOp50");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_ready, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_ready");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_0, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_0");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_1, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_1");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_2, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_2");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_3, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_3");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_4, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_4");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_5, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_5");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_6, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_6");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_7, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_7");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_8, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_8");
    sc_trace(mVcdFile, call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_9, "call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_9");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to15, "ap_idle_pp0_0to15");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

myproject::~myproject() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30;
    delete grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36;
    delete call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50;
}

void myproject::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter15 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter15 = ap_enable_reg_pp0_iter14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter16 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter16 = ap_enable_reg_pp0_iter15.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        layer2_out_0_V_reg_149 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_0.read();
        layer2_out_1_V_reg_154 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_1.read();
        layer2_out_2_V_reg_159 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_2.read();
        layer2_out_3_V_reg_164 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_3.read();
        layer2_out_4_V_reg_169 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_4.read();
        layer2_out_5_V_reg_174 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_5.read();
        layer2_out_6_V_reg_179 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_6.read();
        layer2_out_7_V_reg_184 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_7.read();
        layer2_out_8_V_reg_189 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_8.read();
        layer2_out_9_V_reg_194 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_9.read();
        layer3_out_0_V_reg_199 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_0.read();
        layer3_out_1_V_reg_204 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_1.read();
        layer3_out_2_V_reg_209 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_2.read();
        layer3_out_3_V_reg_214 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_3.read();
        layer3_out_4_V_reg_219 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_4.read();
        layer3_out_5_V_reg_224 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_5.read();
        layer3_out_6_V_reg_229 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_6.read();
        layer3_out_7_V_reg_234 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_7.read();
        layer3_out_8_V_reg_239 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_8.read();
        layer3_out_9_V_reg_244 = call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_9.read();
    }
}

void myproject::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[0];
}

void myproject::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
  esl_seteq<1,1,1>(ap_const_logic_0, input1_V_ap_vld.read())));
}

void myproject::thread_ap_block_pp0_stage0_11001_ignoreCallOp19() {
    ap_block_pp0_stage0_11001_ignoreCallOp19 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
  esl_seteq<1,1,1>(ap_const_logic_0, input1_V_ap_vld.read())));
}

void myproject::thread_ap_block_pp0_stage0_11001_ignoreCallOp50() {
    ap_block_pp0_stage0_11001_ignoreCallOp50 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
  esl_seteq<1,1,1>(ap_const_logic_0, input1_V_ap_vld.read())));
}

void myproject::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || 
  esl_seteq<1,1,1>(ap_const_logic_0, input1_V_ap_vld.read())));
}

void myproject::thread_ap_block_state10_pp0_stage0_iter9() {
    ap_block_state10_pp0_stage0_iter9 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state10_pp0_stage0_iter9_ignore_call26() {
    ap_block_state10_pp0_stage0_iter9_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state10_pp0_stage0_iter9_ignore_call4() {
    ap_block_state10_pp0_stage0_iter9_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state11_pp0_stage0_iter10() {
    ap_block_state11_pp0_stage0_iter10 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state11_pp0_stage0_iter10_ignore_call26() {
    ap_block_state11_pp0_stage0_iter10_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state11_pp0_stage0_iter10_ignore_call4() {
    ap_block_state11_pp0_stage0_iter10_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state12_pp0_stage0_iter11() {
    ap_block_state12_pp0_stage0_iter11 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state12_pp0_stage0_iter11_ignore_call26() {
    ap_block_state12_pp0_stage0_iter11_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state12_pp0_stage0_iter11_ignore_call4() {
    ap_block_state12_pp0_stage0_iter11_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state13_pp0_stage0_iter12() {
    ap_block_state13_pp0_stage0_iter12 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state13_pp0_stage0_iter12_ignore_call26() {
    ap_block_state13_pp0_stage0_iter12_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state13_pp0_stage0_iter12_ignore_call4() {
    ap_block_state13_pp0_stage0_iter12_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state14_pp0_stage0_iter13() {
    ap_block_state14_pp0_stage0_iter13 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state14_pp0_stage0_iter13_ignore_call26() {
    ap_block_state14_pp0_stage0_iter13_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state14_pp0_stage0_iter13_ignore_call4() {
    ap_block_state14_pp0_stage0_iter13_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state15_pp0_stage0_iter14() {
    ap_block_state15_pp0_stage0_iter14 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state15_pp0_stage0_iter14_ignore_call26() {
    ap_block_state15_pp0_stage0_iter14_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state15_pp0_stage0_iter14_ignore_call4() {
    ap_block_state15_pp0_stage0_iter14_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state16_pp0_stage0_iter15() {
    ap_block_state16_pp0_stage0_iter15 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state16_pp0_stage0_iter15_ignore_call26() {
    ap_block_state16_pp0_stage0_iter15_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state16_pp0_stage0_iter15_ignore_call4() {
    ap_block_state16_pp0_stage0_iter15_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state17_pp0_stage0_iter16() {
    ap_block_state17_pp0_stage0_iter16 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state17_pp0_stage0_iter16_ignore_call26() {
    ap_block_state17_pp0_stage0_iter16_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state17_pp0_stage0_iter16_ignore_call4() {
    ap_block_state17_pp0_stage0_iter16_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input1_V_ap_vld.read()));
}

void myproject::thread_ap_block_state1_pp0_stage0_iter0_ignore_call26() {
    ap_block_state1_pp0_stage0_iter0_ignore_call26 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input1_V_ap_vld.read()));
}

void myproject::thread_ap_block_state1_pp0_stage0_iter0_ignore_call4() {
    ap_block_state1_pp0_stage0_iter0_ignore_call4 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, input1_V_ap_vld.read()));
}

void myproject::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state2_pp0_stage0_iter1_ignore_call26() {
    ap_block_state2_pp0_stage0_iter1_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state2_pp0_stage0_iter1_ignore_call4() {
    ap_block_state2_pp0_stage0_iter1_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state3_pp0_stage0_iter2() {
    ap_block_state3_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state3_pp0_stage0_iter2_ignore_call26() {
    ap_block_state3_pp0_stage0_iter2_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state3_pp0_stage0_iter2_ignore_call4() {
    ap_block_state3_pp0_stage0_iter2_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state4_pp0_stage0_iter3() {
    ap_block_state4_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state4_pp0_stage0_iter3_ignore_call26() {
    ap_block_state4_pp0_stage0_iter3_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state4_pp0_stage0_iter3_ignore_call4() {
    ap_block_state4_pp0_stage0_iter3_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state5_pp0_stage0_iter4() {
    ap_block_state5_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state5_pp0_stage0_iter4_ignore_call26() {
    ap_block_state5_pp0_stage0_iter4_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state5_pp0_stage0_iter4_ignore_call4() {
    ap_block_state5_pp0_stage0_iter4_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state6_pp0_stage0_iter5() {
    ap_block_state6_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state6_pp0_stage0_iter5_ignore_call26() {
    ap_block_state6_pp0_stage0_iter5_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state6_pp0_stage0_iter5_ignore_call4() {
    ap_block_state6_pp0_stage0_iter5_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state7_pp0_stage0_iter6() {
    ap_block_state7_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state7_pp0_stage0_iter6_ignore_call26() {
    ap_block_state7_pp0_stage0_iter6_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state7_pp0_stage0_iter6_ignore_call4() {
    ap_block_state7_pp0_stage0_iter6_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state8_pp0_stage0_iter7() {
    ap_block_state8_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state8_pp0_stage0_iter7_ignore_call26() {
    ap_block_state8_pp0_stage0_iter7_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state8_pp0_stage0_iter7_ignore_call4() {
    ap_block_state8_pp0_stage0_iter7_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state9_pp0_stage0_iter8() {
    ap_block_state9_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state9_pp0_stage0_iter8_ignore_call26() {
    ap_block_state9_pp0_stage0_iter8_ignore_call26 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_block_state9_pp0_stage0_iter8_ignore_call4() {
    ap_block_state9_pp0_stage0_iter8_ignore_call4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void myproject::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter16.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void myproject::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void myproject::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void myproject::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void myproject::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void myproject::thread_ap_idle_pp0_0to15() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()))) {
        ap_idle_pp0_0to15 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to15 = ap_const_logic_0;
    }
}

void myproject::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void myproject::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to15.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void myproject::thread_ap_return_0() {
    ap_return_0 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_0.read();
}

void myproject::thread_ap_return_1() {
    ap_return_1 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_1.read();
}

void myproject::thread_ap_return_2() {
    ap_return_2 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_2.read();
}

void myproject::thread_ap_return_3() {
    ap_return_3 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_3.read();
}

void myproject::thread_ap_return_4() {
    ap_return_4 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_4.read();
}

void myproject::thread_ap_return_5() {
    ap_return_5 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_5.read();
}

void myproject::thread_ap_return_6() {
    ap_return_6 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_6.read();
}

void myproject::thread_ap_return_7() {
    ap_return_7 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_7.read();
}

void myproject::thread_ap_return_8() {
    ap_return_8 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_8.read();
}

void myproject::thread_ap_return_9() {
    ap_return_9 = grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_9.read();
}

void myproject::thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp19.read(), ap_const_boolean_0))) {
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce = ap_const_logic_1;
    } else {
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce = ap_const_logic_0;
    }
}

void myproject::thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp50.read(), ap_const_boolean_0))) {
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce = ap_const_logic_1;
    } else {
        grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce = ap_const_logic_0;
    }
}

void myproject::thread_input1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        input1_V_blk_n = input1_V_ap_vld.read();
    } else {
        input1_V_blk_n = ap_const_logic_1;
    }
}

void myproject::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

