// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _myproject_HH_
#define _myproject_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_latency_0_0_0_0_0_0_0_0_0_0_0_1.h"
#include "dense_latency_0_0_0_0_0_0_0_0_0_0_0.h"
#include "relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s.h"

namespace ap_rtl {

struct myproject : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_logic > input1_V_ap_vld;
    sc_in< sc_lv<5184> > input1_V;
    sc_out< sc_lv<16> > ap_return_0;
    sc_out< sc_lv<16> > ap_return_1;
    sc_out< sc_lv<16> > ap_return_2;
    sc_out< sc_lv<16> > ap_return_3;
    sc_out< sc_lv<16> > ap_return_4;
    sc_out< sc_lv<16> > ap_return_5;
    sc_out< sc_lv<16> > ap_return_6;
    sc_out< sc_lv<16> > ap_return_7;
    sc_out< sc_lv<16> > ap_return_8;
    sc_out< sc_lv<16> > ap_return_9;
    sc_out< sc_logic > input1_V_blk_n;


    // Module declarations
    myproject(sc_module_name name);
    SC_HAS_PROCESS(myproject);

    ~myproject();

    sc_trace_file* mVcdFile;

    dense_latency_0_0_0_0_0_0_0_0_0_0_0_1* grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30;
    dense_latency_0_0_0_0_0_0_0_0_0_0_0* grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36;
    relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s* call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter6;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter7;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter8;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter9;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter10;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter11;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter12;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter13;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter14;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter15;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter16;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter8;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter9;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter10;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter11;
    sc_signal< bool > ap_block_state13_pp0_stage0_iter12;
    sc_signal< bool > ap_block_state14_pp0_stage0_iter13;
    sc_signal< bool > ap_block_state15_pp0_stage0_iter14;
    sc_signal< bool > ap_block_state16_pp0_stage0_iter15;
    sc_signal< bool > ap_block_state17_pp0_stage0_iter16;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<16> > layer2_out_0_V_reg_149;
    sc_signal< sc_lv<16> > layer2_out_1_V_reg_154;
    sc_signal< sc_lv<16> > layer2_out_2_V_reg_159;
    sc_signal< sc_lv<16> > layer2_out_3_V_reg_164;
    sc_signal< sc_lv<16> > layer2_out_4_V_reg_169;
    sc_signal< sc_lv<16> > layer2_out_5_V_reg_174;
    sc_signal< sc_lv<16> > layer2_out_6_V_reg_179;
    sc_signal< sc_lv<16> > layer2_out_7_V_reg_184;
    sc_signal< sc_lv<16> > layer2_out_8_V_reg_189;
    sc_signal< sc_lv<16> > layer2_out_9_V_reg_194;
    sc_signal< sc_lv<16> > layer3_out_0_V_reg_199;
    sc_signal< sc_lv<16> > layer3_out_1_V_reg_204;
    sc_signal< sc_lv<16> > layer3_out_2_V_reg_209;
    sc_signal< sc_lv<16> > layer3_out_3_V_reg_214;
    sc_signal< sc_lv<16> > layer3_out_4_V_reg_219;
    sc_signal< sc_lv<16> > layer3_out_5_V_reg_224;
    sc_signal< sc_lv<16> > layer3_out_6_V_reg_229;
    sc_signal< sc_lv<16> > layer3_out_7_V_reg_234;
    sc_signal< sc_lv<16> > layer3_out_8_V_reg_239;
    sc_signal< sc_lv<16> > layer3_out_9_V_reg_244;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_0;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_1;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_2;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_3;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_4;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_5;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_6;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_7;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_8;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_return_9;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0_ignore_call4;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1_ignore_call4;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2_ignore_call4;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3_ignore_call4;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4_ignore_call4;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5_ignore_call4;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6_ignore_call4;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7_ignore_call4;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter8_ignore_call4;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter9_ignore_call4;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter10_ignore_call4;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter11_ignore_call4;
    sc_signal< bool > ap_block_state13_pp0_stage0_iter12_ignore_call4;
    sc_signal< bool > ap_block_state14_pp0_stage0_iter13_ignore_call4;
    sc_signal< bool > ap_block_state15_pp0_stage0_iter14_ignore_call4;
    sc_signal< bool > ap_block_state16_pp0_stage0_iter15_ignore_call4;
    sc_signal< bool > ap_block_state17_pp0_stage0_iter16_ignore_call4;
    sc_signal< bool > ap_block_pp0_stage0_11001_ignoreCallOp19;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_0;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_1;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_2;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_3;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_4;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_5;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_6;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_7;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_8;
    sc_signal< sc_lv<16> > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_return_9;
    sc_signal< sc_logic > grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0_ignore_call26;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1_ignore_call26;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2_ignore_call26;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3_ignore_call26;
    sc_signal< bool > ap_block_state5_pp0_stage0_iter4_ignore_call26;
    sc_signal< bool > ap_block_state6_pp0_stage0_iter5_ignore_call26;
    sc_signal< bool > ap_block_state7_pp0_stage0_iter6_ignore_call26;
    sc_signal< bool > ap_block_state8_pp0_stage0_iter7_ignore_call26;
    sc_signal< bool > ap_block_state9_pp0_stage0_iter8_ignore_call26;
    sc_signal< bool > ap_block_state10_pp0_stage0_iter9_ignore_call26;
    sc_signal< bool > ap_block_state11_pp0_stage0_iter10_ignore_call26;
    sc_signal< bool > ap_block_state12_pp0_stage0_iter11_ignore_call26;
    sc_signal< bool > ap_block_state13_pp0_stage0_iter12_ignore_call26;
    sc_signal< bool > ap_block_state14_pp0_stage0_iter13_ignore_call26;
    sc_signal< bool > ap_block_state15_pp0_stage0_iter14_ignore_call26;
    sc_signal< bool > ap_block_state16_pp0_stage0_iter15_ignore_call26;
    sc_signal< bool > ap_block_state17_pp0_stage0_iter16_ignore_call26;
    sc_signal< bool > ap_block_pp0_stage0_11001_ignoreCallOp50;
    sc_signal< sc_logic > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_ready;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_0;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_1;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_2;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_3;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_4;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_5;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_6;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_7;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_8;
    sc_signal< sc_lv<16> > call_ret1_relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_fu_50_ap_return_9;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0_0to15;
    sc_signal< sc_logic > ap_reset_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_pp0_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_11001_ignoreCallOp19();
    void thread_ap_block_pp0_stage0_11001_ignoreCallOp50();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state10_pp0_stage0_iter9();
    void thread_ap_block_state10_pp0_stage0_iter9_ignore_call26();
    void thread_ap_block_state10_pp0_stage0_iter9_ignore_call4();
    void thread_ap_block_state11_pp0_stage0_iter10();
    void thread_ap_block_state11_pp0_stage0_iter10_ignore_call26();
    void thread_ap_block_state11_pp0_stage0_iter10_ignore_call4();
    void thread_ap_block_state12_pp0_stage0_iter11();
    void thread_ap_block_state12_pp0_stage0_iter11_ignore_call26();
    void thread_ap_block_state12_pp0_stage0_iter11_ignore_call4();
    void thread_ap_block_state13_pp0_stage0_iter12();
    void thread_ap_block_state13_pp0_stage0_iter12_ignore_call26();
    void thread_ap_block_state13_pp0_stage0_iter12_ignore_call4();
    void thread_ap_block_state14_pp0_stage0_iter13();
    void thread_ap_block_state14_pp0_stage0_iter13_ignore_call26();
    void thread_ap_block_state14_pp0_stage0_iter13_ignore_call4();
    void thread_ap_block_state15_pp0_stage0_iter14();
    void thread_ap_block_state15_pp0_stage0_iter14_ignore_call26();
    void thread_ap_block_state15_pp0_stage0_iter14_ignore_call4();
    void thread_ap_block_state16_pp0_stage0_iter15();
    void thread_ap_block_state16_pp0_stage0_iter15_ignore_call26();
    void thread_ap_block_state16_pp0_stage0_iter15_ignore_call4();
    void thread_ap_block_state17_pp0_stage0_iter16();
    void thread_ap_block_state17_pp0_stage0_iter16_ignore_call26();
    void thread_ap_block_state17_pp0_stage0_iter16_ignore_call4();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state1_pp0_stage0_iter0_ignore_call26();
    void thread_ap_block_state1_pp0_stage0_iter0_ignore_call4();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state2_pp0_stage0_iter1_ignore_call26();
    void thread_ap_block_state2_pp0_stage0_iter1_ignore_call4();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state3_pp0_stage0_iter2_ignore_call26();
    void thread_ap_block_state3_pp0_stage0_iter2_ignore_call4();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_block_state4_pp0_stage0_iter3_ignore_call26();
    void thread_ap_block_state4_pp0_stage0_iter3_ignore_call4();
    void thread_ap_block_state5_pp0_stage0_iter4();
    void thread_ap_block_state5_pp0_stage0_iter4_ignore_call26();
    void thread_ap_block_state5_pp0_stage0_iter4_ignore_call4();
    void thread_ap_block_state6_pp0_stage0_iter5();
    void thread_ap_block_state6_pp0_stage0_iter5_ignore_call26();
    void thread_ap_block_state6_pp0_stage0_iter5_ignore_call4();
    void thread_ap_block_state7_pp0_stage0_iter6();
    void thread_ap_block_state7_pp0_stage0_iter6_ignore_call26();
    void thread_ap_block_state7_pp0_stage0_iter6_ignore_call4();
    void thread_ap_block_state8_pp0_stage0_iter7();
    void thread_ap_block_state8_pp0_stage0_iter7_ignore_call26();
    void thread_ap_block_state8_pp0_stage0_iter7_ignore_call4();
    void thread_ap_block_state9_pp0_stage0_iter8();
    void thread_ap_block_state9_pp0_stage0_iter8_ignore_call26();
    void thread_ap_block_state9_pp0_stage0_iter8_ignore_call4();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp0_0to15();
    void thread_ap_ready();
    void thread_ap_reset_idle_pp0();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
    void thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_1_fu_30_ap_ce();
    void thread_grp_dense_latency_0_0_0_0_0_0_0_0_0_0_0_fu_36_ap_ce();
    void thread_input1_V_blk_n();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
