// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::ap_const_logic_1 = sc_dt::Log_1;
const bool relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::ap_const_boolean_1 = true;
const sc_lv<16> relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<15> relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::ap_const_lv15_0 = "000000000000000";
const sc_logic relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::ap_const_logic_0 = sc_dt::Log_0;

relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( zext_ln81_fu_122_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( zext_ln81_1_fu_144_p1 );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( zext_ln81_2_fu_166_p1 );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( zext_ln81_3_fu_188_p1 );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( zext_ln81_4_fu_210_p1 );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( zext_ln81_5_fu_232_p1 );

    SC_METHOD(thread_ap_return_6);
    sensitive << ( zext_ln81_6_fu_254_p1 );

    SC_METHOD(thread_ap_return_7);
    sensitive << ( zext_ln81_7_fu_276_p1 );

    SC_METHOD(thread_ap_return_8);
    sensitive << ( zext_ln81_8_fu_298_p1 );

    SC_METHOD(thread_ap_return_9);
    sensitive << ( zext_ln81_9_fu_320_p1 );

    SC_METHOD(thread_icmp_ln1494_1_fu_126_p2);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_icmp_ln1494_2_fu_148_p2);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_icmp_ln1494_3_fu_170_p2);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_icmp_ln1494_4_fu_192_p2);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_icmp_ln1494_5_fu_214_p2);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_icmp_ln1494_6_fu_236_p2);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_icmp_ln1494_7_fu_258_p2);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_icmp_ln1494_8_fu_280_p2);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_icmp_ln1494_9_fu_302_p2);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_icmp_ln1494_fu_104_p2);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_select_ln81_1_fu_136_p3);
    sensitive << ( icmp_ln1494_1_fu_126_p2 );
    sensitive << ( trunc_ln81_1_fu_132_p1 );

    SC_METHOD(thread_select_ln81_2_fu_158_p3);
    sensitive << ( icmp_ln1494_2_fu_148_p2 );
    sensitive << ( trunc_ln81_2_fu_154_p1 );

    SC_METHOD(thread_select_ln81_3_fu_180_p3);
    sensitive << ( icmp_ln1494_3_fu_170_p2 );
    sensitive << ( trunc_ln81_3_fu_176_p1 );

    SC_METHOD(thread_select_ln81_4_fu_202_p3);
    sensitive << ( icmp_ln1494_4_fu_192_p2 );
    sensitive << ( trunc_ln81_4_fu_198_p1 );

    SC_METHOD(thread_select_ln81_5_fu_224_p3);
    sensitive << ( icmp_ln1494_5_fu_214_p2 );
    sensitive << ( trunc_ln81_5_fu_220_p1 );

    SC_METHOD(thread_select_ln81_6_fu_246_p3);
    sensitive << ( icmp_ln1494_6_fu_236_p2 );
    sensitive << ( trunc_ln81_6_fu_242_p1 );

    SC_METHOD(thread_select_ln81_7_fu_268_p3);
    sensitive << ( icmp_ln1494_7_fu_258_p2 );
    sensitive << ( trunc_ln81_7_fu_264_p1 );

    SC_METHOD(thread_select_ln81_8_fu_290_p3);
    sensitive << ( icmp_ln1494_8_fu_280_p2 );
    sensitive << ( trunc_ln81_8_fu_286_p1 );

    SC_METHOD(thread_select_ln81_9_fu_312_p3);
    sensitive << ( icmp_ln1494_9_fu_302_p2 );
    sensitive << ( trunc_ln81_9_fu_308_p1 );

    SC_METHOD(thread_select_ln81_fu_114_p3);
    sensitive << ( icmp_ln1494_fu_104_p2 );
    sensitive << ( trunc_ln81_fu_110_p1 );

    SC_METHOD(thread_trunc_ln81_1_fu_132_p1);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_trunc_ln81_2_fu_154_p1);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_trunc_ln81_3_fu_176_p1);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_trunc_ln81_4_fu_198_p1);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_trunc_ln81_5_fu_220_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_trunc_ln81_6_fu_242_p1);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_trunc_ln81_7_fu_264_p1);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_trunc_ln81_8_fu_286_p1);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_trunc_ln81_9_fu_308_p1);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_trunc_ln81_fu_110_p1);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_zext_ln81_1_fu_144_p1);
    sensitive << ( select_ln81_1_fu_136_p3 );

    SC_METHOD(thread_zext_ln81_2_fu_166_p1);
    sensitive << ( select_ln81_2_fu_158_p3 );

    SC_METHOD(thread_zext_ln81_3_fu_188_p1);
    sensitive << ( select_ln81_3_fu_180_p3 );

    SC_METHOD(thread_zext_ln81_4_fu_210_p1);
    sensitive << ( select_ln81_4_fu_202_p3 );

    SC_METHOD(thread_zext_ln81_5_fu_232_p1);
    sensitive << ( select_ln81_5_fu_224_p3 );

    SC_METHOD(thread_zext_ln81_6_fu_254_p1);
    sensitive << ( select_ln81_6_fu_246_p3 );

    SC_METHOD(thread_zext_ln81_7_fu_276_p1);
    sensitive << ( select_ln81_7_fu_268_p3 );

    SC_METHOD(thread_zext_ln81_8_fu_298_p1);
    sensitive << ( select_ln81_8_fu_290_p3 );

    SC_METHOD(thread_zext_ln81_9_fu_320_p1);
    sensitive << ( select_ln81_9_fu_312_p3 );

    SC_METHOD(thread_zext_ln81_fu_122_p1);
    sensitive << ( select_ln81_fu_114_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
    sc_trace(mVcdFile, ap_return_6, "(port)ap_return_6");
    sc_trace(mVcdFile, ap_return_7, "(port)ap_return_7");
    sc_trace(mVcdFile, ap_return_8, "(port)ap_return_8");
    sc_trace(mVcdFile, ap_return_9, "(port)ap_return_9");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, icmp_ln1494_fu_104_p2, "icmp_ln1494_fu_104_p2");
    sc_trace(mVcdFile, trunc_ln81_fu_110_p1, "trunc_ln81_fu_110_p1");
    sc_trace(mVcdFile, select_ln81_fu_114_p3, "select_ln81_fu_114_p3");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_126_p2, "icmp_ln1494_1_fu_126_p2");
    sc_trace(mVcdFile, trunc_ln81_1_fu_132_p1, "trunc_ln81_1_fu_132_p1");
    sc_trace(mVcdFile, select_ln81_1_fu_136_p3, "select_ln81_1_fu_136_p3");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_148_p2, "icmp_ln1494_2_fu_148_p2");
    sc_trace(mVcdFile, trunc_ln81_2_fu_154_p1, "trunc_ln81_2_fu_154_p1");
    sc_trace(mVcdFile, select_ln81_2_fu_158_p3, "select_ln81_2_fu_158_p3");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_170_p2, "icmp_ln1494_3_fu_170_p2");
    sc_trace(mVcdFile, trunc_ln81_3_fu_176_p1, "trunc_ln81_3_fu_176_p1");
    sc_trace(mVcdFile, select_ln81_3_fu_180_p3, "select_ln81_3_fu_180_p3");
    sc_trace(mVcdFile, icmp_ln1494_4_fu_192_p2, "icmp_ln1494_4_fu_192_p2");
    sc_trace(mVcdFile, trunc_ln81_4_fu_198_p1, "trunc_ln81_4_fu_198_p1");
    sc_trace(mVcdFile, select_ln81_4_fu_202_p3, "select_ln81_4_fu_202_p3");
    sc_trace(mVcdFile, icmp_ln1494_5_fu_214_p2, "icmp_ln1494_5_fu_214_p2");
    sc_trace(mVcdFile, trunc_ln81_5_fu_220_p1, "trunc_ln81_5_fu_220_p1");
    sc_trace(mVcdFile, select_ln81_5_fu_224_p3, "select_ln81_5_fu_224_p3");
    sc_trace(mVcdFile, icmp_ln1494_6_fu_236_p2, "icmp_ln1494_6_fu_236_p2");
    sc_trace(mVcdFile, trunc_ln81_6_fu_242_p1, "trunc_ln81_6_fu_242_p1");
    sc_trace(mVcdFile, select_ln81_6_fu_246_p3, "select_ln81_6_fu_246_p3");
    sc_trace(mVcdFile, icmp_ln1494_7_fu_258_p2, "icmp_ln1494_7_fu_258_p2");
    sc_trace(mVcdFile, trunc_ln81_7_fu_264_p1, "trunc_ln81_7_fu_264_p1");
    sc_trace(mVcdFile, select_ln81_7_fu_268_p3, "select_ln81_7_fu_268_p3");
    sc_trace(mVcdFile, icmp_ln1494_8_fu_280_p2, "icmp_ln1494_8_fu_280_p2");
    sc_trace(mVcdFile, trunc_ln81_8_fu_286_p1, "trunc_ln81_8_fu_286_p1");
    sc_trace(mVcdFile, select_ln81_8_fu_290_p3, "select_ln81_8_fu_290_p3");
    sc_trace(mVcdFile, icmp_ln1494_9_fu_302_p2, "icmp_ln1494_9_fu_302_p2");
    sc_trace(mVcdFile, trunc_ln81_9_fu_308_p1, "trunc_ln81_9_fu_308_p1");
    sc_trace(mVcdFile, select_ln81_9_fu_312_p3, "select_ln81_9_fu_312_p3");
    sc_trace(mVcdFile, zext_ln81_fu_122_p1, "zext_ln81_fu_122_p1");
    sc_trace(mVcdFile, zext_ln81_1_fu_144_p1, "zext_ln81_1_fu_144_p1");
    sc_trace(mVcdFile, zext_ln81_2_fu_166_p1, "zext_ln81_2_fu_166_p1");
    sc_trace(mVcdFile, zext_ln81_3_fu_188_p1, "zext_ln81_3_fu_188_p1");
    sc_trace(mVcdFile, zext_ln81_4_fu_210_p1, "zext_ln81_4_fu_210_p1");
    sc_trace(mVcdFile, zext_ln81_5_fu_232_p1, "zext_ln81_5_fu_232_p1");
    sc_trace(mVcdFile, zext_ln81_6_fu_254_p1, "zext_ln81_6_fu_254_p1");
    sc_trace(mVcdFile, zext_ln81_7_fu_276_p1, "zext_ln81_7_fu_276_p1");
    sc_trace(mVcdFile, zext_ln81_8_fu_298_p1, "zext_ln81_8_fu_298_p1");
    sc_trace(mVcdFile, zext_ln81_9_fu_320_p1, "zext_ln81_9_fu_320_p1");
#endif

    }
}

relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::~relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_0() {
    ap_return_0 = zext_ln81_fu_122_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_1() {
    ap_return_1 = zext_ln81_1_fu_144_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_2() {
    ap_return_2 = zext_ln81_2_fu_166_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_3() {
    ap_return_3 = zext_ln81_3_fu_188_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_4() {
    ap_return_4 = zext_ln81_4_fu_210_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_5() {
    ap_return_5 = zext_ln81_5_fu_232_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_6() {
    ap_return_6 = zext_ln81_6_fu_254_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_7() {
    ap_return_7 = zext_ln81_7_fu_276_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_8() {
    ap_return_8 = zext_ln81_8_fu_298_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_ap_return_9() {
    ap_return_9 = zext_ln81_9_fu_320_p1.read();
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_1_fu_126_p2() {
    icmp_ln1494_1_fu_126_p2 = (!data_1_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_1_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_2_fu_148_p2() {
    icmp_ln1494_2_fu_148_p2 = (!data_2_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_2_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_3_fu_170_p2() {
    icmp_ln1494_3_fu_170_p2 = (!data_3_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_3_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_4_fu_192_p2() {
    icmp_ln1494_4_fu_192_p2 = (!data_4_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_4_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_5_fu_214_p2() {
    icmp_ln1494_5_fu_214_p2 = (!data_5_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_5_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_6_fu_236_p2() {
    icmp_ln1494_6_fu_236_p2 = (!data_6_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_6_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_7_fu_258_p2() {
    icmp_ln1494_7_fu_258_p2 = (!data_7_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_7_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_8_fu_280_p2() {
    icmp_ln1494_8_fu_280_p2 = (!data_8_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_8_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_9_fu_302_p2() {
    icmp_ln1494_9_fu_302_p2 = (!data_9_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_9_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_icmp_ln1494_fu_104_p2() {
    icmp_ln1494_fu_104_p2 = (!data_0_V_read.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_0_V_read.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_1_fu_136_p3() {
    select_ln81_1_fu_136_p3 = (!icmp_ln1494_1_fu_126_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_1_fu_126_p2.read()[0].to_bool())? trunc_ln81_1_fu_132_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_2_fu_158_p3() {
    select_ln81_2_fu_158_p3 = (!icmp_ln1494_2_fu_148_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_2_fu_148_p2.read()[0].to_bool())? trunc_ln81_2_fu_154_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_3_fu_180_p3() {
    select_ln81_3_fu_180_p3 = (!icmp_ln1494_3_fu_170_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_3_fu_170_p2.read()[0].to_bool())? trunc_ln81_3_fu_176_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_4_fu_202_p3() {
    select_ln81_4_fu_202_p3 = (!icmp_ln1494_4_fu_192_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_4_fu_192_p2.read()[0].to_bool())? trunc_ln81_4_fu_198_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_5_fu_224_p3() {
    select_ln81_5_fu_224_p3 = (!icmp_ln1494_5_fu_214_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_5_fu_214_p2.read()[0].to_bool())? trunc_ln81_5_fu_220_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_6_fu_246_p3() {
    select_ln81_6_fu_246_p3 = (!icmp_ln1494_6_fu_236_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_6_fu_236_p2.read()[0].to_bool())? trunc_ln81_6_fu_242_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_7_fu_268_p3() {
    select_ln81_7_fu_268_p3 = (!icmp_ln1494_7_fu_258_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_7_fu_258_p2.read()[0].to_bool())? trunc_ln81_7_fu_264_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_8_fu_290_p3() {
    select_ln81_8_fu_290_p3 = (!icmp_ln1494_8_fu_280_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_8_fu_280_p2.read()[0].to_bool())? trunc_ln81_8_fu_286_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_9_fu_312_p3() {
    select_ln81_9_fu_312_p3 = (!icmp_ln1494_9_fu_302_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_9_fu_302_p2.read()[0].to_bool())? trunc_ln81_9_fu_308_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_select_ln81_fu_114_p3() {
    select_ln81_fu_114_p3 = (!icmp_ln1494_fu_104_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_fu_104_p2.read()[0].to_bool())? trunc_ln81_fu_110_p1.read(): ap_const_lv15_0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_1_fu_132_p1() {
    trunc_ln81_1_fu_132_p1 = data_1_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_2_fu_154_p1() {
    trunc_ln81_2_fu_154_p1 = data_2_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_3_fu_176_p1() {
    trunc_ln81_3_fu_176_p1 = data_3_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_4_fu_198_p1() {
    trunc_ln81_4_fu_198_p1 = data_4_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_5_fu_220_p1() {
    trunc_ln81_5_fu_220_p1 = data_5_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_6_fu_242_p1() {
    trunc_ln81_6_fu_242_p1 = data_6_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_7_fu_264_p1() {
    trunc_ln81_7_fu_264_p1 = data_7_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_8_fu_286_p1() {
    trunc_ln81_8_fu_286_p1 = data_8_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_9_fu_308_p1() {
    trunc_ln81_9_fu_308_p1 = data_9_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_trunc_ln81_fu_110_p1() {
    trunc_ln81_fu_110_p1 = data_0_V_read.read().range(15-1, 0);
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_1_fu_144_p1() {
    zext_ln81_1_fu_144_p1 = esl_zext<16,15>(select_ln81_1_fu_136_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_2_fu_166_p1() {
    zext_ln81_2_fu_166_p1 = esl_zext<16,15>(select_ln81_2_fu_158_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_3_fu_188_p1() {
    zext_ln81_3_fu_188_p1 = esl_zext<16,15>(select_ln81_3_fu_180_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_4_fu_210_p1() {
    zext_ln81_4_fu_210_p1 = esl_zext<16,15>(select_ln81_4_fu_202_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_5_fu_232_p1() {
    zext_ln81_5_fu_232_p1 = esl_zext<16,15>(select_ln81_5_fu_224_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_6_fu_254_p1() {
    zext_ln81_6_fu_254_p1 = esl_zext<16,15>(select_ln81_6_fu_246_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_7_fu_276_p1() {
    zext_ln81_7_fu_276_p1 = esl_zext<16,15>(select_ln81_7_fu_268_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_8_fu_298_p1() {
    zext_ln81_8_fu_298_p1 = esl_zext<16,15>(select_ln81_8_fu_290_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_9_fu_320_p1() {
    zext_ln81_9_fu_320_p1 = esl_zext<16,15>(select_ln81_9_fu_312_p3.read());
}

void relu_ap_fixed_ap_fixed_16_8_5_3_0_ReLU_config3_s::thread_zext_ln81_fu_122_p1() {
    zext_ln81_fu_122_p1 = esl_zext<16,15>(select_ln81_fu_114_p3.read());
}

}

